#!/bin/sh

# Suppress kernel messages
dmesg -n 1

# Mount file systems
mkdir proc sys
mount -t proc none /proc      # ps
mount -t sysfs none /sys      # sys/class/net/eth0
mount -t devtmpfs none /dev   # dev/urandom (https)

# Setup Static IP
ifconfig eth0 10.0.2.15
route add default gw 10.0.2.2

# Shell
setsid cttyhack sh -c "/etc/login.sh"